---
# tasks file for copy

 - name: Copying your php file in the /var/www/html
   copy: 
     src: /home/ansible/playbooksmultiplerole/index1.php
     dest: /var/www/html/
     force: yes

   modify: 
       - restart httpd service
