---
- name: Ansible register Module example
  hosts: webservers
  become: true
  tasks:
    - name: starting vsftpd
      service: name=vsftpd state=started enabled=yes

    - name: vsftpd status
      command: service vsftpd status
      register: vsftpd_status

    - name: vsftpd status output
      debug:
        var: vsftpd_status

