---
- hosts: webservers
  tasks:
  - name: Ansible register with_items example
    shell: "find *.html"
    args:
      chdir: "/home/ansible"
    register: with_output

  - shell: "cp {{ item }} {{item}}_bkp"
    with_items:
      - "{{ with_output.stdout_lines }}"
