---
- hosts: webservers
  vars:
    - create_user_file: yes
    - user: sainath
  tasks:
    - name: create file for user
      file:
        path: /home/{{ ansible }}/myfile
        state: touch
      when: create_user_file
