---
# tasks file for http
 - name: install httpd pkg
   yum: 
    name: httpd
    state: latest

 - name: copy static httpd.conf file
   copy: 
     src: httpd.conf
     dest: /etc/httpd/conf/httpd.conf
   notify: 
     to start service

 - name: jinj2 file copy
   template:
     src: index.j2
     dest: /var/www/html/index.html
